name=OpenBCI_32bit_Library
version=3.1.5
author=Joel Murphy <joel@openbci.com>, Conor Russomanno <conor@openbci.com>, Leif Percifield <lpercifield@gmail.com>, AJ Keller <pushtheworldllc@gmail.com>
maintainer=Ioannis Smanis <ioannis@openbci.com>, Richard Waltman <richard@openbci.com>, Tharun Iyer <tharun@openbci.com>
sentence=The library for collecting data using the OpenBCI Cyton (32bit) boards.
paragraph=This library is designed to be used with the PIC32MX250F128B. Use the DefaultBoard.ino for the firmware that ships with the Cyton. See the examples for stripped down versions of the board. See the learning pages at docs.openbci.com for more info!
category=Device Control
url=https://github.com/OpenBCI/OpenBCI_32bit_Library
architectures=pic32
